[package]
name = "darkbio-wire-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.darkbio-wire]
path = ".."
features = ["fuzz"]

[[bin]]
name = "ark_protocol"
path = "fuzz_targets/ark_protocol.rs"
test = false
doc = false
bench = false

[[bin]]
name = "host_protocol"
path = "fuzz_targets/host_protocol.rs"
test = false
doc = false
bench = false
