// wire-rs: encrypted protocol between Ark and host
// Copyright 2025 Dark Bio AG. All rights reserved.

#![no_main]

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;
use std::io::sink;

use darkbio_cobs as cobs;
use darkbio_wire::{Error, HostSide, MAX_FRAME_SIZE};

/// Maximum packet size generated by the fuzzer. Anything that COBS-encodes to
/// above MAX_FRAME_SIZE should be discarded.
const MAX_FUZZ_PACKET_SIZE: u32 = 4 * MAX_FRAME_SIZE as u32;

/// Maximum total data size to avoid going OOM from too many too large chunks.
const MAX_TOTAL_SIZE: usize = 64 * 1024 * 1024;

/// Fuzz dataset consisting of packet sizes to generate and COBS-encode. Packet
/// content is always 0x01 bytes since the wire protocol only cares about the
/// zero delimiter, not the content itself.
#[derive(Arbitrary, Debug)]
struct Input {
    packet_sizes: Vec<u32>,
}

fuzz_target!(|input: Input| {
    // Iterate over the "desired" packet sizes and discard anything above some
    // sanity threshold
    let mut total_size = 0usize;
    let packet_sizes: Vec<u32> = input
        .packet_sizes
        .iter()
        .map(|&s| s % (MAX_FUZZ_PACKET_SIZE + 1))
        .take_while(|&s| {
            let encoded_size = cobs::encode_buffer(s as usize);
            total_size += encoded_size + 1;
            total_size <= MAX_TOTAL_SIZE
        })
        .collect();

    // Flatten the packets into a single data transport
    let wire_data: Vec<u8> = packet_sizes
        .iter()
        .flat_map(|&s| {
            let packet = vec![1u8; s as usize];
            let encoded_size = cobs::encode_buffer(s as usize);

            let mut encoded = vec![0u8; encoded_size];
            let len = cobs::encode(&packet, &mut encoded).unwrap();
            encoded.truncate(len);
            encoded.push(0);
            encoded
        })
        .collect();

    let mut wire = HostSide::new(wire_data.as_slice(), sink());

    // Collect the expected packet sizes, discarding anything that COBS-encodes
    // above the wire frame threshold
    let expected_sizes: Vec<u32> = packet_sizes
        .iter()
        .filter(|&&s| cobs::encode_buffer(s as usize) <= MAX_FRAME_SIZE)
        .copied()
        .collect();

    // Keep consuming packets and checking against the expected list
    let mut packet_idx = 0;
    loop {
        match wire.next_packet_blob() {
            Ok(None) => {} // empty frame (session reset signal), skip
            Ok(Some(packet)) => {
                assert!(
                    packet_idx < expected_sizes.len(),
                    "received more packets than expected"
                );
                let expected_size = expected_sizes[packet_idx] as usize;
                assert_eq!(
                    packet.len(),
                    expected_size,
                    "packet {} size mismatch",
                    packet_idx
                );
                assert!(
                    packet.iter().all(|&b| b == 1),
                    "packet {} content mismatch",
                    packet_idx
                );
                packet_idx += 1;
            }
            Err(Error::Terminated) => break,
            Err(_) => {}
        }
    }
    assert_eq!(packet_idx, expected_sizes.len(), "packet count mismatch");
});
