// wire-rs: encrypted protocol between Ark and host
// Copyright 2025 Dark Bio AG. All rights reserved.

#![no_main]

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;
use std::io::{self, Read, sink};

use darkbio_wire::{Error, HostSide, MAX_FRAME_SIZE};

/// Maximum frame size generated by the fuzzer. Anything above MAX_FRAME_SIZE
/// should be discarded.
const MAX_FUZZ_FRAME_SIZE: u32 = 4 * MAX_FRAME_SIZE as u32;

/// Maximum total data size to avoid going OOM from too many too large chunks.
const MAX_TOTAL_SIZE: usize = 64 * 1024 * 1024;

/// Fuzz dataset consisting of frame sizes and various chunk sizes to split them
/// into when feeding into the transport. Frame content is always 0x01 bytes since
/// the wire protocol only cares about the zero delimiter, not the content itself.
#[derive(Arbitrary, Debug)]
struct Input {
    frame_sizes: Vec<u32>,
    chunk_sizes: Vec<u16>,
}

/// Specialized reader that returns its input data in smaller chunks to simulate
/// various fragmentation scenarios.
struct ChunkedReader {
    data: Vec<u8>,
    pos: usize,
    chunks: Vec<u16>,
    chunk_idx: usize,
}

impl ChunkedReader {
    fn new(data: Vec<u8>, chunk_sizes: Vec<u16>) -> Self {
        Self {
            data,
            pos: 0,
            chunks: chunk_sizes,
            chunk_idx: 0,
        }
    }
}

impl Read for ChunkedReader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        // If the reader is exhausted, return EOF
        if self.pos >= self.data.len() {
            return Ok(0);
        }
        // Retrieve the next chunk size, defaulting to everything at the end
        let chunk_size = if self.chunks.is_empty() {
            buf.len()
        } else {
            let size = self.chunks[self.chunk_idx % self.chunks.len()] as usize;
            self.chunk_idx += 1;
            size.max(1)
        };

        let available = self.data.len() - self.pos;
        let to_read = chunk_size.min(available).min(buf.len());

        buf[..to_read].copy_from_slice(&self.data[self.pos..self.pos + to_read]);
        self.pos += to_read;

        Ok(to_read)
    }
}

fuzz_target!(|input: Input| {
    // Iterate over the "desired" frame sizes and discard anything above some
    // sanity threshold
    let mut total_size = 0usize;
    let frame_sizes: Vec<u32> = input
        .frame_sizes
        .iter()
        .map(|&s| s % (MAX_FUZZ_FRAME_SIZE + 1))
        .take_while(|&s| {
            total_size += s as usize + 1;
            total_size <= MAX_TOTAL_SIZE
        })
        .collect();

    // Flatten the frames into a single data transport and create a chunked
    // delivery system
    let wire_data: Vec<u8> = frame_sizes
        .iter()
        .flat_map(|&s| {
            let mut bytes = vec![1u8; s as usize];
            bytes.push(0);
            bytes
        })
        .collect();

    let reader = ChunkedReader::new(wire_data, input.chunk_sizes);
    let mut wire = HostSide::new(reader, sink());

    // Collect the expected read sizes, discarding anything above the wire frame
    // threshold
    let expected_sizes: Vec<u32> = frame_sizes
        .iter()
        .filter(|&&s| (s as usize) <= MAX_FRAME_SIZE)
        .copied()
        .collect();

    // Keep consuming frames and checking it against the desired list
    let mut frame_idx = 0;
    loop {
        match wire.next_frame_blob() {
            Ok(frame) => {
                assert!(
                    frame_idx < expected_sizes.len(),
                    "received more frames than expected"
                );
                let expected_size = expected_sizes[frame_idx] as usize;
                assert_eq!(
                    frame.len(),
                    expected_size,
                    "frame {} size mismatch",
                    frame_idx
                );
                assert!(
                    frame.iter().all(|&b| b == 1),
                    "frame {} content mismatch",
                    frame_idx
                );
                frame_idx += 1;
            }
            Err(Error::Terminated) => break,
            Err(_) => {}
        }
    }
    assert_eq!(frame_idx, expected_sizes.len(), "frame count mismatch");
});
